spring:
  application:
    name: notification-service
  config:
    import: "optional:configserver:http://3.111.235.72:8888"
  kafka:
    consumer:
      bootstrap-servers: 65.1.243.55:9093 # Update with the correct IP address and port
      group-id: OneMoreRep-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            value:
              default:
                type: 'com.ashish.notificationservice.dto.MsgDTO'
            type:
              mapping: 'com.ashish.planservice.dto.MsgDTO:com.ashish.notificationservice.dto.MsgDTO'

  mail:
    host: smtp.gmail.com
    username: onemorerep24x7@gmail.com
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true
    password: ddsziehyitvjrrqk

server:
  port: 8084

eureka:
  instance:
    host: localhost
  client:
    service-url:
      defaultZone: http://3.111.235.72:8761/eureka